#!/bin/sh

while read oldrev newrev refname
do
  count=$(git rev-list --count $oldrev..$newrev)

  if [ $count -gt 1 ]; then
    echo "❌ Push rejected: more than 1 commit is not allowed."
    exit 1
  fi
done